# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "96537e7709726d5f3d4b41a0ec1c46d0"
name = "Hubex Marketplace"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_products,write_orders"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[build]
automatically_update_urls_on_dev = true
